FROM phusion/passenger-full:1.0.13
MAINTAINER EverTrue <devops@evertrue.com>

WORKDIR /home/app/webapp

CMD ["/sbin/my_init"]

EXPOSE 8080

RUN bash -lc 'rvm install ruby-2.4.1'
RUN bash -lc 'rvm --default use ruby-2.4.1'

COPY base-nginx.conf /etc/nginx/nginx.conf
COPY nginx-ruby24.conf /etc/nginx/sites-enabled/default

RUN gem install vault -v 0.10.1

COPY bin /etc/my_init.d

# https://github.com/phusion/passenger-docker/issues/224
RUN rm -f /var/log/nginx/error.log
