FROM phusion/passenger-ruby21:0.9.19
MAINTAINER EverTrue <devops@evertrue.com>

WORKDIR /home/app/webapp

CMD ["/sbin/my_init"]

EXPOSE 8080

RUN bash -lc 'rvm --default use ruby-2.1.9'

COPY nginx-ruby21.conf /etc/nginx/sites-enabled/default

# Install Vault and AWS Secrets Manager for credential storage
RUN gem install vault -v 0.10.1
RUN gem install aws-sdk-secretsmanager -v 1.6.0

COPY bin /etc/my_init.d
