FROM phusion/passenger-ruby27:latest
MAINTAINER EverTrue <devops@evertrue.com>

WORKDIR /home/app/webapp

CMD ["/sbin/my_init"]

EXPOSE 8080

COPY libssl.list /etc/apt/sources.list.d/libssl.list
RUN apt update && apt-cache policy libssl1.0-dev
RUN apt-get -y install libssl1.0-dev
RUN bash -lc 'rvm get stable'
RUN bash -lc 'rvm install ruby-2.1.9'
RUN bash -lc 'rvm --default use ruby-2.1.9'

COPY base-nginx.conf /etc/nginx/nginx.conf
COPY nginx-ruby21.conf /etc/nginx/sites-enabled/default

# Install Vault and AWS Secrets Manager for credential storage
RUN gem install vault -v 0.10.1
RUN gem install aws-sdk-secretsmanager -v 1.6.0

COPY bin /etc/my_init.d

# https://github.com/phusion/passenger-docker/issues/224
RUN rm -f /var/log/nginx/error.log
