FROM phusion/passenger-ruby23:0.9.22
MAINTAINER EverTrue <devops@evertrue.com>

WORKDIR /home/app/webapp

CMD ["/sbin/my_init"]

EXPOSE 8080

RUN bash -lc 'rvm --default use ruby-2.3.3'

COPY nginx-ruby23.conf /etc/nginx/sites-enabled/default

RUN gem install vault -v 0.4.0

COPY bin /etc/my_init.d
