FROM phusion/passenger-ruby25:0.9.35
MAINTAINER EverTrue <devops@evertrue.com>

WORKDIR /home/app/webapp

CMD ["/sbin/my_init"]

EXPOSE 8080

RUN bash -lc 'rvm --default use ruby-2.5.1'

COPY base-nginx.conf /etc/nginx/nginx.conf
COPY nginx-ruby25.conf /etc/nginx/sites-enabled/default

# Install Vault and AWS Secrets Manager for credential storage
RUN gem install vault -v 0.10.1
RUN gem install aws-sdk-secretsmanager -v 1.6.0

COPY bin /etc/my_init.d

# https://github.com/phusion/passenger-docker/issues/224
RUN rm -f /var/log/nginx/error.log
